version: "3.5"

services:
  bot:
    image: ddoss-bot:latest
    env_file:
      - .env
    build:
      context: .
      network: host
    network_mode: host
    command:
      - watchfiles
      - "python bot.py"
      - src/
      - bot.py
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5555"
  scheduler:
    image: ddoss-bot:latest
    env_file:
      - .env
    network_mode: host
    command:
      - watchfiles
      - "python scheduler.py"
      - src/
      - scheduler.py
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5555"
  db:
    image: "postgres:15-bullseye"
    ports:
      - 5555:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
